Algoritmo "Lista 2 Ex - 3"
// Disciplina  :  [APC]
// Professor   : João Victor
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/04/2019
Var
   num :inteiro


Inicio
   escreval("Digite um número inteiro")
   leia(num)
   se num mod 2 = 0 entao
      escreval(num," é primo")
   senao
      escreval(num," não é primo")
   fimse
Fimalgoritmo